options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/sonar-api:latest',
        '-f', 'Dockerfile',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/sonar-api:latest'
      ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'sonar-api',
        '--image', 'gcr.io/$PROJECT_ID/sonar-api:latest',
        '--region', 'europe-west2',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--add-cloudsql-instances', 'final-year-project-489111:europe-west2:final-year-project',
        '--set-env-vars', 'BUCKET_NAME=sonar_uploads,DB_NAME=Sonar,DB_USER=app_user,DB_PASS=Cooper14?,INSTANCE_CONNECTION_NAME=final-year-project-489111:europe-west2:final-year-project'
      ]

images:
  - 'gcr.io/$PROJECT_ID/sonar-api:latest'
